# Generated by Django 6.0.6 on 2026-09-08 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='department_code',
            new_name='department_name',
        ),
    ]
