# Generated by Django 6.0.6 on 2026-09-10 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employee_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_id', models.CharField(max_length=20, unique=True)),
                ('reason', models.TextField(blank=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('manager', models.CharField(max_length=20)),
                ('leave_type', models.CharField(max_length=30)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
        ),
    ]
