# Generated by Django 6.0.6 on 2026-09-10 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_leave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='leave_id',
        ),
    ]
