# Generated by Django 6.0.6 on 2026-09-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_remove_leave_leave_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
